apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myApp
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
      - image: narenp/gems:latest
        name: gems
        envFrom:
        - configMapRef:
            name: my-cm        
